//
// Copyright 2024 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package resources

const (
	// Default User Management CR
	UserMgmtCR = "AccountIAM"
	// UserMgmtOperator is the subscription name of User Management Operator
	UserMgmtOperator = "ibm-user-management-operator"
	// OperatorIBMApiVersion is the api version of IBM Operator
	OperatorIBMApiVersion = "operator.ibm.com/v1alpha1"
	// Default OperandRequest
	UserMgmtOpreq = "ibm-user-management-request"
	// OpreqKind is the kind of OperandConfig
	OpreqKind = "OperandRequest"
	// SericeKind is the kind of Service
	ServiceKind = "Service"
	// SecretKind is the kind of Secret
	SecretKind = "Secret"
	// RouteKind is the kind of Route
	RouteKind = "Route"
	// RouteAPIGroup is the api group of Route
	RouteAPIGroup = "route.openshift.io"
	// Version is the version of some resources
	Version = "v1"
	// JobKind is the kind of Job
	JobKind = "Job"
	// JobAPIGroup is the api group of Job
	JobAPIGroup = "batch/v1"
	// CSCASecret is the name of the secret for CA certificate
	CSCASecret = "cs-ca-certificate-secret"
	// RedisCertKey is the key of Redis CA Certificate
	CAKey = "ca.crt"
	// RedisOperator is the subscription name of Redis Operator
	RedisOperator = "ibm-redis-cp-operator"
	// RedisKind is the kind of Redis
	RedisKind = "Rediscp"
	// RedisAPIGroup is the api group of Redis
	RedisAPIGroup = "redis.ibm.com"
	// RedisStatus is the status field in Redis CR
	RedisStatus = "redisStatus"
	//RedisURLssl
	RedisURLssl = "redis-url-ssl"
	//RedisPassword
	RedisPassword = "auth"
	// IMPackage is the name of IM Operator
	IMPackage = "ibm-im-operator"
	// EDBClusterKind is the kind of Cluster
	EDBClusterKind = "Cluster"
	// EDBAPIGroupVersion is the api group version of Cluster
	EDBAPIGroupVersion = "postgresql.k8s.enterprisedb.io/v1"
	// BootstrapSecret is the name of the secret for user management bootstrap
	BootstrapSecret = "user-mgmt-bootstrap"
	// IMOIDCCrendential is the secret where the IM OIDC credential is stored
	IMOIDCCrendential = "ibm-iam-bindinfo-platform-oidc-credentials"
	// IMPlatformCM is the configmap where the auth idp related information is stored
	IMPlatformCM = "platform-auth-idp"
	// WLPClientID is the key in the secret.data where the WLP client ID is stored
	WLPClientID = "WLP_CLIENT_ID"
	// MCSPAPIKey is the MCSP API key generated by calling MCSP API Key Management API
	MCSPAPIKey = "API_KEY"
	// SkipAnnotations is the annotation to skip the update of the operand resrouces
	SkipAnnotation = "operator.ibm.com/ibm-user-management-operator.skip-update"
	//HashedData is the key for checking the checksum of data section
	HashedData string = "operator.ibm.com/ibm-user-management-operator.hashedData"
)

func prefixed(accountIAMName, suffix string) string {
	if suffix == "" {
		return accountIAMName
	}
	return accountIAMName + "-" + suffix
}

// AccountIAM returns the Account IAM service/route base name for the given CR
func AccountIAM(accountIAMName string) string {
	return prefixed(accountIAMName, "account-iam")
}

// Rediscp returns the Redis custom resource name for the given CR
func Rediscp(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-redis")
}

// RedisCACert returns the Redis CA certificate secret name for the given CR
func RedisCACert(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-redis-ca-cert")
}

// RedisSVCCert returns the Redis service certificate secret name for the given CR
func RedisSVCCert(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-redis-svc-tls-cert")
}

// CreateDBJob returns the database creation job name for the given CR
func CreateDBJob(accountIAMName string) string {
	return prefixed(accountIAMName, "create-db")
}

// DBMigrationJob returns the database migration job name for the given CR
func DBMigrationJob(accountIAMName string) string {
	return prefixed(accountIAMName, "db-migration")
}

// AccountIAMDBSecret returns the Account IAM database secret name for the given CR
func AccountIAMDBSecret(accountIAMName string) string {
	return prefixed(accountIAMName, "database-secret")
}

// AccountIAMConfigSecret returns the Account IAM mpconfig secret name for the given CR
func AccountIAMConfigSecret(accountIAMName string) string {
	return prefixed(accountIAMName, "mpconfig-secrets")
}

// AccountIAMOidcClientAuth returns the Account IAM OIDC client auth secret name for the given CR
func AccountIAMOidcClientAuth(accountIAMName string) string {
	return prefixed(accountIAMName, "oidc-client-auth")
}

// AccountIAMOKDAuth returns the Account IAM OKD auth secret name for the given CR
func AccountIAMOKDAuth(accountIAMName string) string {
	return prefixed(accountIAMName, "okd-auth")
}

// AccountIAMUISecrets returns the Account IAM UI secret name for the given CR
func AccountIAMUISecrets(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-secrets")
}

// AccountIAMUIRoute returns the Account IAM UI route name for the given CR
func AccountIAMUIRoute(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-account")
}

// AccountIAMUIAPIInstance returns the Account IAM UI API instance route name for the given CR
func AccountIAMUIAPIInstance(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-api-instance")
}

// AccountIAMUIAPIService returns the Account IAM UI API service name for the given CR
func AccountIAMUIAPIService(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-api-service")
}

// AccountIAMUIService returns the Account IAM UI account service name for the given CR
func AccountIAMUIService(accountIAMName string) string {
	return prefixed(accountIAMName, "ui-account-service")
}

// AccountIAMCACert returns the Account IAM CA certificate secret name for the given CR
func AccountIAMCACert(accountIAMName string) string {
	return prefixed(accountIAMName, "ca-cert")
}

// AccountIAMSVCCert returns the Account IAM service certificate secret name for the given CR
func AccountIAMSVCCert(accountIAMName string) string {
	return prefixed(accountIAMName, "svc-tls-cert")
}

// IMConfigJob returns the IM configuration job name for the given CR
func IMConfigJob(accountIAMName string) string {
	return prefixed(accountIAMName, "im-config-job")
}

// IMAPISecret returns the IM API secret name for the given CR
func IMAPISecret(accountIAMName string) string {
	return prefixed(accountIAMName, "im-integration-details")
}

// NamePrefix returns the reusable prefix (crName-) for templates
func NamePrefix(accountIAMName string) string {
	if accountIAMName == "" {
		return ""
	}
	return accountIAMName + "-"
}
