---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-ibm-com-v1alpha1-accountiam
  failurePolicy: Fail
  name: maccountiam.kb.io
  rules:
  - apiGroups:
    - operator.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accountiams
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-ibm-com-v1alpha1-accountiam
  failurePolicy: Fail
  name: vaccountiam.kb.io
  rules:
  - apiGroups:
    - operator.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accountiams
  sideEffects: None
